### ISSUE TITLE
clicks at buffer change

### ISSUE THREAD

**Issue by yuxshao** [yuxshao/ptweb#1]
For some more complex songs, there's an audible click every 1.6 seconds or so, at a buffer change. In fact, this artefact seems to persist even when a completely silent song is loaded afterwards, and even if the offending song isn't even started before being swapped out with the silent song.

**Comment by metallicLurker** [comment]
I have noted more about issue: the clicks occur regardless of the volume setting. Upon recording them in Audacity, I've noticed that the clicks on the left stereo track look identical to each other, and so do the clicks on the right stereo track. This possibly means that something is creating them. I have mentioned the waveform amplitude discontinuity, but it seems that it's irrelevant here. (I apologize for not being able to help further with this, I do not know JavaScript.)

**Comment by yuxshao** [comment]
Oh, that's really interesting - for me, if I set the volume down the clicks also get quieter too. Maybe we're hearing different things. If you can get the clicks to show up on a silent piece, could you upload a recording of what you hear? (maybe at least 10sec) Thanks again for the help!

**Comment by metallicLurker** [comment]
I have looked further into this using Audacity. [Here are the files used while doing this, including the Blank.ptcop, 2 recordings of clicks made in Audacity, one Audacity project (just in case) and waves of the clicks screenshot.](https://github.com/yuxshao/ptweb/files/2225662/Observation.on.clicks.in.PtWeb.zip)
I have triggered the clicks 2 separate times in a blank .ptcop. What I've noticed:
1) The clicks do get quieter/louder when adjusting volume. (Shown in Exhibit 1a at 100%, Exhibit 1b at 50% volume) They otherwise do not change. Peculiarly, clicks hardly ever happen in the _right_ stereo track, and when they do, they're nearly unnoticeable.
2) The clicks created are not constant, they're random with each upload. This may indicate a glitch. (Comparing Exhibits 1a and 2) In the previous observation, the waves of the clicks in rip_in_wip.ptcop was also different from the clicks shown in the images.

**Comment by yuxshao** [comment]
Ah, so it looks like it is the same as what I'm experiencing. That it only shows up on the left side makes it especially annoying to listen to. I'll do a few tests when I get the time later today/tomorrow and try to figure out what's causing it.

**Comment by yuxshao** [comment]
Fixed in https://github.com/yuxshao/pxtnDecoder/commit/99a193fe66e58fcb2d1acdfa5153c0df80402bee - it was just a memory thing. Code was trying to get the contents of the next chunk of audio after declaring that that space in memory was free for writing other stuff to. Demo should be updated.
